-- Fresh PostgreSQL 16+ schema, equivalent to SQLite migrations 001–027.
-- SQLite retains its upgrade history. Future schema changes need a migration
-- for every supported dialect. Date strings remain UTC for API compatibility.

CREATE TABLE "researches" (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "goal" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'active',
    "instruction" TEXT NOT NULL DEFAULT '',
    "memory" TEXT NOT NULL DEFAULT '[]',
    "tags" TEXT NOT NULL DEFAULT '[]',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "code" TEXT NOT NULL DEFAULT '',
    "user_id" TEXT DEFAULT NULL ,
    "team_id" TEXT DEFAULT NULL ,
    "template_slug" TEXT NOT NULL DEFAULT '',
    "template_version" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "sections" (
    "id" TEXT PRIMARY KEY,
    "research_id" TEXT NOT NULL ,
    "name" TEXT NOT NULL,
    "display_name" TEXT NOT NULL DEFAULT '',
    "description" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "code" TEXT NOT NULL DEFAULT '',
    "field_spec" TEXT NOT NULL DEFAULT '[]',
    "spec_version" INTEGER NOT NULL DEFAULT 0,
    UNIQUE(research_id, name)
);

CREATE TABLE "entries" (
    "id" TEXT PRIMARY KEY,
    "research_id" TEXT NOT NULL ,
    "section_id" TEXT NOT NULL ,
    "title" TEXT NOT NULL DEFAULT '',
    "content" TEXT NOT NULL DEFAULT '',
    "description" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'draft',
    "tags" TEXT NOT NULL DEFAULT '[]',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "code" TEXT NOT NULL DEFAULT '',
    "session_id" TEXT DEFAULT NULL ,
    "entry_type" TEXT NOT NULL DEFAULT 'markdown',
    "metadata" TEXT NOT NULL DEFAULT '{}',
    "spec_version" INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE "sessions" (
    "id" TEXT PRIMARY KEY,
    "research_id" TEXT NOT NULL ,
    "title" TEXT NOT NULL DEFAULT '',
    "focus" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'active',
    "notes" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "code" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "questions" (
    "id" TEXT PRIMARY KEY,
    "session_id" TEXT NOT NULL ,
    "text" TEXT NOT NULL,
    "area" TEXT NOT NULL DEFAULT '',
    "rationale" TEXT NOT NULL DEFAULT '',
    "priority" TEXT NOT NULL DEFAULT 'medium',
    "status" TEXT NOT NULL DEFAULT 'pending',
    "answer" TEXT NOT NULL DEFAULT '',
    "parent_id" TEXT DEFAULT NULL,
    "position" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "code" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "tasks" (
    "id" TEXT PRIMARY KEY,
    "research_id" TEXT NOT NULL ,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "status" TEXT NOT NULL DEFAULT 'pending',
    "priority" TEXT NOT NULL DEFAULT 'medium',
    "result" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "completed_at" TEXT DEFAULT NULL,
    "code" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "crossrefs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    "source_type" TEXT NOT NULL DEFAULT 'entry',
    "source_id" TEXT NOT NULL DEFAULT '',
    "source_entry_id" TEXT DEFAULT NULL,
    "source_research_id" TEXT NOT NULL,
    "target_entry_id" TEXT DEFAULT NULL,
    "target_research_id" TEXT DEFAULT NULL,
    "target_ref" TEXT NOT NULL,
    "resolved" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "target_roadmap_id" TEXT DEFAULT NULL,
    "target_node_id" TEXT DEFAULT NULL
);

CREATE TABLE "users" (
    "id" TEXT PRIMARY KEY,
    "email" TEXT NOT NULL UNIQUE,
    "password_hash" TEXT NOT NULL,
    "name" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "api_keys" (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL ,
    "name" TEXT NOT NULL DEFAULT '',
    "key_hash" TEXT NOT NULL UNIQUE,
    "key_prefix" TEXT NOT NULL,
    "last_used_at" TEXT,
    "expires_at" TEXT,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "oauth_clients" (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT DEFAULT NULL ,
    "secret_hash" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "redirect_uris" TEXT NOT NULL DEFAULT '[]',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "oauth_codes" (
    "code" TEXT PRIMARY KEY,
    "client_id" TEXT NOT NULL ,
    "user_id" TEXT NOT NULL ,
    "redirect_uri" TEXT NOT NULL,
    "scope" TEXT NOT NULL DEFAULT '',
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "code_challenge" TEXT NOT NULL DEFAULT '',
    "code_challenge_method" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "oauth_tokens" (
    "id" TEXT PRIMARY KEY,
    "client_id" TEXT NOT NULL ,
    "user_id" TEXT NOT NULL ,
    "access_token_hash" TEXT NOT NULL UNIQUE,
    "refresh_token_hash" TEXT NOT NULL DEFAULT '',
    "scope" TEXT NOT NULL DEFAULT '',
    "expires_at" TEXT NOT NULL,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "external_links" (
    "id" TEXT PRIMARY KEY,
    "source_type" TEXT NOT NULL DEFAULT 'entry',
    "source_id" TEXT NOT NULL,
    "research_id" TEXT NOT NULL ,
    "url" TEXT NOT NULL,
    "title" TEXT NOT NULL DEFAULT '',
    "domain" TEXT NOT NULL DEFAULT '',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "roadmaps" (
    "id" TEXT PRIMARY KEY,
    "code" TEXT NOT NULL DEFAULT '',
    "research_id" TEXT NOT NULL ,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "statuses" TEXT NOT NULL DEFAULT '[]',
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "stages" TEXT NOT NULL DEFAULT '[]',
    "view" TEXT NOT NULL DEFAULT 'graph'
);

CREATE TABLE "roadmap_nodes" (
    "id" TEXT PRIMARY KEY,
    "code" TEXT NOT NULL DEFAULT '',
    "roadmap_id" TEXT NOT NULL ,
    "title" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "node_type" TEXT NOT NULL DEFAULT 'step',
    "status" TEXT NOT NULL DEFAULT '',
    "position_x" REAL NOT NULL DEFAULT 0,
    "position_y" REAL NOT NULL DEFAULT 0,
    "parent_id" TEXT DEFAULT NULL,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "ref_type" TEXT,
    "ref_id" TEXT,
    "metadata" TEXT,
    "stage" TEXT NOT NULL DEFAULT '',
    "node_date" TEXT NOT NULL DEFAULT '',
    "node_end_date" TEXT NOT NULL DEFAULT ''
);

CREATE TABLE "roadmap_edges" (
    "id" TEXT PRIMARY KEY,
    "roadmap_id" TEXT NOT NULL ,
    "source_node_id" TEXT NOT NULL ,
    "target_node_id" TEXT NOT NULL ,
    "label" TEXT NOT NULL DEFAULT '',
    "edge_type" TEXT NOT NULL DEFAULT 'default',
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "entry_blocks" (
    "entry_id" TEXT    NOT NULL ,
    "research_id" TEXT    NOT NULL ,
    "block_id" TEXT    NOT NULL,
    "position" INTEGER NOT NULL,
    "type" TEXT    NOT NULL,
    "data" TEXT    NOT NULL DEFAULT '{}',
    "state" TEXT    NOT NULL DEFAULT '',
    PRIMARY KEY (entry_id, block_id)
);

CREATE TABLE "entry_revisions" (
    "id" TEXT PRIMARY KEY,
    "entry_id" TEXT    NOT NULL ,
    "research_id" TEXT    NOT NULL ,
    "revision" INTEGER NOT NULL,
    "title" TEXT    NOT NULL DEFAULT '',
    "description" TEXT    NOT NULL DEFAULT '',
    "content" TEXT    NOT NULL DEFAULT '',
    "entry_type" TEXT    NOT NULL DEFAULT 'markdown',
    "status" TEXT    NOT NULL DEFAULT '',
    "tags" TEXT    NOT NULL DEFAULT '[]',
    "author_kind" TEXT    NOT NULL DEFAULT 'agent',
    "session_id" TEXT,
    "user_id" TEXT,
    "summary" TEXT    NOT NULL DEFAULT '',
    "created_at" TEXT    NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "metadata" TEXT NOT NULL DEFAULT '{}',
    "spec_version" INTEGER NOT NULL DEFAULT 0,
    UNIQUE(entry_id, revision)
);

CREATE TABLE "teams" (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "personal" INTEGER NOT NULL DEFAULT 0,
    "created_by" TEXT DEFAULT NULL ,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "team_members" (
    "team_id" TEXT NOT NULL ,
    "user_id" TEXT NOT NULL ,
    "role" TEXT NOT NULL DEFAULT 'viewer',
    "invited_by" TEXT DEFAULT NULL ,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (team_id, user_id)
);

CREATE TABLE "team_invites" (
    "id" TEXT PRIMARY KEY,
    "team_id" TEXT NOT NULL ,
    "email" TEXT NOT NULL DEFAULT '',
    "role" TEXT NOT NULL DEFAULT 'viewer',
    "token_hash" TEXT NOT NULL UNIQUE,
    "invited_by" TEXT NOT NULL ,
    "expires_at" TEXT NOT NULL,
    "accepted_at" TEXT,
    "accepted_by" TEXT DEFAULT NULL ,
    "revoked_at" TEXT,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "shares" (
    "id" TEXT PRIMARY KEY,
    "token_hash" TEXT NOT NULL UNIQUE,
    "research_id" TEXT NOT NULL ,
    "user_id" TEXT DEFAULT NULL ,
    "scope" TEXT NOT NULL DEFAULT 'research',
    "target_id" TEXT NOT NULL DEFAULT '',
    "label" TEXT NOT NULL DEFAULT '',
    "include" TEXT NOT NULL DEFAULT '{}',
    "password_hash" TEXT NOT NULL DEFAULT '',
    "expires_at" TEXT,
    "revoked_at" TEXT,
    "last_seen_at" TEXT,
    "view_count" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "skills" (
    "id" TEXT PRIMARY KEY,
    "team_id" TEXT ,
    "research_id" TEXT ,
    "user_id" TEXT ,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "body" TEXT NOT NULL DEFAULT '',
    "tier" TEXT NOT NULL DEFAULT 'team',
    "ambient" INTEGER NOT NULL DEFAULT 0,
    "forked_from" TEXT,
    "needs_trigger" INTEGER NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    CHECK (team_id IS NULL OR research_id IS NULL)
);

CREATE TABLE "research_skills" (
    "research_id" TEXT NOT NULL ,
    "skill_id" TEXT NOT NULL ,
    "via_template" INTEGER NOT NULL DEFAULT 0,
    "attached_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (research_id, skill_id)
);

CREATE TABLE "research_templates" (
    "id" TEXT PRIMARY KEY,
    "team_id" TEXT ,
    "user_id" TEXT ,
    "slug" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL DEFAULT '',
    "when_to_use" TEXT NOT NULL DEFAULT '',
    "when_not_to_use" TEXT NOT NULL DEFAULT '',
    "body" TEXT NOT NULL DEFAULT '',
    "skills" TEXT NOT NULL DEFAULT '[]',
    "source" TEXT NOT NULL DEFAULT 'user',
    "forked_from" TEXT,
    "version" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
);

CREATE TABLE "annotations" (
    "id" TEXT PRIMARY KEY,
    "code" TEXT NOT NULL,
    "research_id" TEXT NOT NULL ,
    "entry_id" TEXT NOT NULL ,
    "block_id" TEXT NOT NULL DEFAULT '',
    "quote_exact" TEXT NOT NULL,
    "quote_prefix" TEXT NOT NULL DEFAULT '',
    "quote_suffix" TEXT NOT NULL DEFAULT '',
    "anchored_revision" INTEGER NOT NULL DEFAULT 0,
    "kind" TEXT NOT NULL,
    "body" TEXT NOT NULL DEFAULT '',
    "author_kind" TEXT NOT NULL DEFAULT 'human',
    "user_id" TEXT,
    "status" TEXT NOT NULL DEFAULT 'open',
    "resolution" TEXT NOT NULL DEFAULT '',
    "resolved_revision" INTEGER,
    "session_id" TEXT,
    "task_id" TEXT,
    "rejections" TEXT    NOT NULL DEFAULT '[]',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "created_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "updated_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    "answered_at" TEXT,
    "closed_at" TEXT
);

CREATE TABLE "entry_views" (
    "viewer_id" TEXT NOT NULL,
    "user_id" TEXT ,
    "entry_id" TEXT NOT NULL ,
    "seen_revision" INTEGER NOT NULL CHECK (seen_revision > 0),
    "seen_at" TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'),
    PRIMARY KEY (viewer_id, entry_id),
    CHECK (user_id IS NULL OR viewer_id = user_id)
);

ALTER TABLE "researches" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "researches" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE;

ALTER TABLE "sections" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "entries" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "entries" ADD FOREIGN KEY ("section_id") REFERENCES "sections" ("id") ON DELETE CASCADE;

ALTER TABLE "entries" ADD FOREIGN KEY ("session_id") REFERENCES "sessions" ("id") ON DELETE SET NULL;

ALTER TABLE "sessions" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "questions" ADD FOREIGN KEY ("session_id") REFERENCES "sessions" ("id") ON DELETE CASCADE;

ALTER TABLE "questions" ADD FOREIGN KEY (parent_id) REFERENCES questions(id) ON DELETE SET NULL;

ALTER TABLE "tasks" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "api_keys" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "oauth_clients" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "oauth_codes" ADD FOREIGN KEY ("client_id") REFERENCES "oauth_clients" ("id") ON DELETE CASCADE;

ALTER TABLE "oauth_codes" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "oauth_tokens" ADD FOREIGN KEY ("client_id") REFERENCES "oauth_clients" ("id") ON DELETE CASCADE;

ALTER TABLE "oauth_tokens" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "external_links" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "roadmaps" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "roadmap_nodes" ADD FOREIGN KEY ("roadmap_id") REFERENCES "roadmaps" ("id") ON DELETE CASCADE;

ALTER TABLE "roadmap_edges" ADD FOREIGN KEY ("roadmap_id") REFERENCES "roadmaps" ("id") ON DELETE CASCADE;

ALTER TABLE "roadmap_edges" ADD FOREIGN KEY ("source_node_id") REFERENCES "roadmap_nodes" ("id") ON DELETE CASCADE;

ALTER TABLE "roadmap_edges" ADD FOREIGN KEY ("target_node_id") REFERENCES "roadmap_nodes" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_blocks" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_blocks" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_revisions" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_revisions" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "teams" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "team_members" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE;

ALTER TABLE "team_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "team_members" ADD FOREIGN KEY ("invited_by") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "team_invites" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE;

ALTER TABLE "team_invites" ADD FOREIGN KEY ("invited_by") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "team_invites" ADD FOREIGN KEY ("accepted_by") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "shares" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "shares" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "skills" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE;

ALTER TABLE "skills" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "skills" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "research_skills" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "research_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") ON DELETE CASCADE;

ALTER TABLE "research_templates" ADD FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON DELETE CASCADE;

ALTER TABLE "research_templates" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "annotations" ADD FOREIGN KEY ("research_id") REFERENCES "researches" ("id") ON DELETE CASCADE;

ALTER TABLE "annotations" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_views" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "entry_views" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id") ON DELETE CASCADE;

CREATE INDEX idx_researches_status ON researches(status);

CREATE INDEX idx_sections_research ON sections(research_id);

CREATE INDEX idx_entries_section ON entries(section_id);

CREATE INDEX idx_entries_research ON entries(research_id);

CREATE INDEX idx_sessions_research ON sessions(research_id);

CREATE INDEX idx_sessions_status ON sessions(status);

CREATE INDEX idx_questions_session ON questions(session_id);

CREATE INDEX idx_questions_parent ON questions(parent_id);

CREATE INDEX idx_questions_status ON questions(status);

CREATE INDEX idx_tasks_research ON tasks(research_id);

CREATE INDEX idx_tasks_status ON tasks(status);

CREATE UNIQUE INDEX idx_researches_code ON researches(code) WHERE code != '';

CREATE UNIQUE INDEX idx_entries_code_research ON entries(research_id, code) WHERE code != '';

CREATE UNIQUE INDEX idx_sections_code_research ON sections(research_id, code) WHERE code != '';

CREATE UNIQUE INDEX idx_sessions_code_research ON sessions(research_id, code) WHERE code != '';

CREATE UNIQUE INDEX idx_questions_code_session ON questions(session_id, code) WHERE code != '';

CREATE UNIQUE INDEX idx_tasks_code_research ON tasks(research_id, code) WHERE code != '';

CREATE INDEX idx_crossrefs_source ON crossrefs(source_type, source_id);

CREATE INDEX idx_crossrefs_source_research ON crossrefs(source_research_id);

CREATE INDEX idx_crossrefs_target_entry ON crossrefs(target_entry_id);

CREATE INDEX idx_api_keys_user ON api_keys(user_id);

CREATE INDEX idx_researches_user ON researches(user_id);

CREATE INDEX idx_entries_session ON entries(session_id);

CREATE INDEX idx_external_links_research ON external_links(research_id);

CREATE INDEX idx_external_links_source ON external_links(source_type, source_id);

CREATE INDEX idx_external_links_domain ON external_links(domain);

CREATE INDEX idx_roadmaps_research ON roadmaps(research_id);

CREATE INDEX idx_roadmap_nodes_roadmap ON roadmap_nodes(roadmap_id);

CREATE INDEX idx_roadmap_nodes_parent ON roadmap_nodes(parent_id);

CREATE INDEX idx_roadmap_edges_roadmap ON roadmap_edges(roadmap_id);

CREATE INDEX idx_roadmap_edges_source ON roadmap_edges(source_node_id);

CREATE INDEX idx_roadmap_edges_target ON roadmap_edges(target_node_id);

CREATE INDEX idx_crossrefs_target_roadmap ON crossrefs(target_roadmap_id);

CREATE INDEX idx_entries_type ON entries(entry_type);

CREATE INDEX idx_entry_blocks_order ON entry_blocks(entry_id, position);

CREATE INDEX idx_entry_blocks_research ON entry_blocks(research_id, type);

CREATE INDEX idx_entry_revisions_entry ON entry_revisions(entry_id, revision DESC);

CREATE INDEX idx_entry_revisions_session ON entry_revisions(session_id);

CREATE INDEX idx_entry_revisions_research ON entry_revisions(research_id, created_at);

CREATE INDEX idx_team_members_user ON team_members(user_id);

CREATE INDEX idx_team_invites_team ON team_invites(team_id);

CREATE INDEX idx_researches_team ON researches(team_id);

CREATE INDEX idx_shares_research ON shares(research_id);

CREATE UNIQUE INDEX idx_skills_builtin_slug
    ON skills(slug) WHERE team_id IS NULL AND research_id IS NULL;

CREATE UNIQUE INDEX idx_skills_team_slug
    ON skills(team_id, slug) WHERE team_id IS NOT NULL;

CREATE UNIQUE INDEX idx_skills_private_slug
    ON skills(research_id, slug) WHERE research_id IS NOT NULL;

CREATE INDEX idx_research_skills_skill ON research_skills(skill_id);

CREATE UNIQUE INDEX idx_templates_global_slug
    ON research_templates(slug) WHERE team_id IS NULL;

CREATE UNIQUE INDEX idx_templates_team_slug
    ON research_templates(team_id, slug) WHERE team_id IS NOT NULL;

CREATE INDEX idx_annotations_queue ON annotations(research_id, status);

CREATE INDEX idx_annotations_entry ON annotations(entry_id, block_id);

CREATE INDEX idx_entry_views_entry ON entry_views(entry_id);

INSERT INTO teams (id, name, personal) VALUES ('team-local', 'Local', 0);
